-- SCHEMA: bio

-- CATALOGO DE FLUJOS
----------------------------------
CREATE TABLE [bio].[INCODE_FLOW] (
     [ID]          VARCHAR(50)  NOT NULL
    ,[NAME]        VARCHAR(50)  NOT NULL
    ,[DESCRIPTION] VARCHAR(250) NOT NULL
    ,[PERSON_TYPE] NVARCHAR(10) CHECK ([PERSON_TYPE] IN ('PF', 'PM', 'AMBOS'))
    ,[PEP]         BIT          NOT NULL CONSTRAINT [DF_INCODE_FLOW_PEP]     DEFAULT 0
    ,[FATCA]       BIT          NOT NULL CONSTRAINT [DF_INCODE_FLOW_FATCA]   DEFAULT 0
    ,[RISK_TYPE]   NVARCHAR(15) CHECK ([RISK_TYPE] IN ('ALTO', 'MEDIO', 'BAJO'))
    ,[CREATED]     DATETIME     NOT NULL CONSTRAINT [DF_INCODE_FLOW_CREATED] DEFAULT GETDATE()
    ,[UPDATED]     DATETIME
    ,[ACTIVE]      BIT          NOT NULL CONSTRAINT [DF_INCODE_FLOW_ACTIVE] DEFAULT 1

    ,CONSTRAINT [PK_INCODE_FLOW_ID]   PRIMARY KEY ([ID])
    ,CONSTRAINT [UQ_INCODE_FLOW_NAME] UNIQUE ([NAME])
);

-- SESIONES INCODE
----------------------------------
CREATE TABLE [bio].[INCODE_SESSION] (
     [ID]         UNIQUEIDENTIFIER
    ,[INTERVIEW]  VARCHAR(50)  NOT NULL
    ,[FLOW]       VARCHAR(50)  NOT NULL
    ,[CLIENT]     VARCHAR(25)  NOT NULL
    ,[TOKEN]      VARCHAR(500) NOT NULL
    ,[CREATED]    DATETIME     NOT NULL CONSTRAINT [DF_INCODE_SESSION_CREATED] DEFAULT GETDATE()
    ,[UPDATED]    DATETIME
    ,[ACTIVE]     BIT          NOT NULL CONSTRAINT [DF_INCODE_SESSION_ACTIVE] DEFAULT 1

    ,CONSTRAINT [PK_INCODE_SESSION_ID]        PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_INCODE_SESSION_FLOW]      FOREIGN KEY ([FLOW]) REFERENCES [bio].[INCODE_FLOW] ([ID])
    ,CONSTRAINT [UQ_INCODE_SESSION_INTERVIEW] UNIQUE      ([INTERVIEW])
);
GO

-- CLIENTES - Tabla principal que almacena información común
----------------------------------
CREATE TABLE [bio].[CLIENTES] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_INCODE_SESSION]    UNIQUEIDENTIFIER
    ,[TIPO_PERSONA]         VARCHAR(2)       NOT NULL CHECK ([TIPO_PERSONA] IN ('PF', 'PM'))
    ,[FECHA_REGISTRO]       DATETIME         NOT NULL CONSTRAINT [DF_CLIENTES_FECHA_REGISTRO] DEFAULT GETDATE()
    ,[ESTATUS]              VARCHAR(20)      NOT NULL CONSTRAINT [DF_CLIENTES_ESTATUS] DEFAULT 'ACTIVO'
    ,[FECHA_MODIFICACION]   DATETIME         NOT NULL CONSTRAINT [DF_CLIENTES_FECHA_MODIFICACION] DEFAULT GETDATE()

    ,CONSTRAINT [PK_CLIENTES_ID]                   PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_CLIENTES_INCODE_SESSION]       FOREIGN KEY ([ID_INCODE_SESSION]) REFERENCES [bio].[INCODE_SESSION] ([ID])
);

-- PERSONAS FISICAS
----------------------------------
CREATE TABLE [bio].[PERSONAS_FISICAS] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]           INT              NOT NULL
    ,[NOMBRE]               VARCHAR(100)     NOT NULL
    ,[SEGUNDO_NOMBRE]       VARCHAR(100)
    ,[PATERNO]              VARCHAR(100)     NOT NULL
    ,[MATERNO]              VARCHAR(100)
    ,[GENERO]               VARCHAR(20)
    ,[FECHA_NACIMIENTO]     DATE
    ,[LUGAR_NACIMIENTO]     VARCHAR(200)
    ,[PAIS_NACIMIENTO]      VARCHAR(100)
    ,[NACIONALIDAD]         VARCHAR(100)
    ,[CIUDADANIA]           VARCHAR(100)
    ,[OCUPACION]            VARCHAR(200)
    ,[ACTIVIDAD]            VARCHAR(200)
    ,[ESTADO_CIVIL]         VARCHAR(50)

    ,CONSTRAINT [PK_PERSONAS_FISICAS_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_PERSONAS_FISICAS_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- PERSONAS MORALES
----------------------------------
CREATE TABLE [bio].[PERSONAS_MORALES] (
     [ID]                           INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]                   INT              NOT NULL
    ,[RAZON_SOCIAL]                 VARCHAR(300)     NOT NULL
    ,[TIPO_SOCIEDAD]                VARCHAR(100)
    ,[LUGAR_CONSTITUCION]           VARCHAR(200)
    ,[FECHA_CONSTITUCION]           DATE
    ,[NACIONALIDAD]                 VARCHAR(100)
    ,[TESTIMONIO]                   VARCHAR(50)
    ,[NUMERO_REGISTRO_PUBLICO]      VARCHAR(50)
    ,[PODERES_REPRESENTANTE_LEGAL]  VARCHAR(50)
    ,[RFC]                          VARCHAR(13)
    ,[TAX_ID]                       VARCHAR(50)

    ,CONSTRAINT [PK_PERSONAS_MORALES_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_PERSONAS_MORALES_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- DIRECCIONES
----------------------------------
CREATE TABLE [bio].[DIRECCIONES] (
     [ID]                       INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]               INT
    ,[ID_REPRESENTANTE_LEGAL]   INT
    ,[TIPO_DIRECCION]           VARCHAR(20)      CHECK ([TIPO_DIRECCION] IN ('FISCAL', 'CONTACTO', 'REPRESENTANTE'))
    ,[CALLE]                    VARCHAR(200)
    ,[EXTERIOR]                 VARCHAR(20)
    ,[INTERIOR]                 VARCHAR(20)
    ,[COLONIA]                  VARCHAR(100)
    ,[MUNICIPIO]                VARCHAR(100)
    ,[CIUDAD]                   VARCHAR(100)
    ,[ENTIDAD_FEDERATIVA]       VARCHAR(100)
    ,[ESTADO]                   VARCHAR(100)
    ,[CODIGO_POSTAL]            VARCHAR(10)

    ,CONSTRAINT [PK_DIRECCIONES_ID]                    PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_DIRECCIONES_CLIENTE]               FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
    ,CONSTRAINT [FK_DIRECCIONES_REPRESENTANTE_LEGAL]   FOREIGN KEY ([ID_REPRESENTANTE_LEGAL]) REFERENCES [bio].[REPRESENTANTES_LEGALES] ([ID])
);

-- CONTACTOS
----------------------------------
CREATE TABLE [bio].[CONTACTOS] (
     [ID]                       INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]               INT
    ,[ID_REPRESENTANTE_LEGAL]   INT
    ,[TIPO_CONTACTO]            VARCHAR(20)      CHECK ([TIPO_CONTACTO] IN ('CLIENTE', 'REPRESENTANTE'))
    ,[TELEFONO]                 VARCHAR(20)
    ,[CELULAR]                  VARCHAR(20)
    ,[LADA]                     VARCHAR(5)
    ,[EMAIL]                    VARCHAR(100)

    ,CONSTRAINT [PK_CONTACTOS_ID]                      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_CONTACTOS_CLIENTE]                 FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
    ,CONSTRAINT [FK_CONTACTOS_REPRESENTANTE_LEGAL]     FOREIGN KEY ([ID_REPRESENTANTE_LEGAL]) REFERENCES [bio].[REPRESENTANTES_LEGALES] ([ID])
);

-- CUENTAS BANCARIAS
----------------------------------
CREATE TABLE [bio].[CUENTAS_BANCARIAS] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]           INT              NOT NULL
    ,[TIPO_CUENTA]          VARCHAR(100)
    ,[NUMERO_CUENTA]        VARCHAR(50)
    ,[CLABE]                VARCHAR(18)

    ,CONSTRAINT [PK_CUENTAS_BANCARIAS_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_CUENTAS_BANCARIAS_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- DOCUMENTACION
----------------------------------
CREATE TABLE [bio].[DOCUMENTACION] (
     [ID]                       INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]               INT
    ,[ID_REPRESENTANTE_LEGAL]   INT
    ,[TIPO_DOCUMENTO]           VARCHAR(20)      CHECK ([TIPO_DOCUMENTO] IN ('CLIENTE', 'REPRESENTANTE'))
    ,[CURP]                     VARCHAR(18)
    ,[RFC]                      VARCHAR(13)
    ,[FIEL]                     VARCHAR(50)
    ,[NUMERO_SERIE_FIEL]        VARCHAR(50)
    ,[INE]                      VARCHAR(20)
    ,[PASAPORTE]                VARCHAR(20)
    ,[CEDULA_PROFESIONAL]       VARCHAR(20)
    ,[FECHA_EXPIRACION]         DATE

    ,CONSTRAINT [PK_DOCUMENTACION_ID]                  PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_DOCUMENTACION_CLIENTE]             FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
    ,CONSTRAINT [FK_DOCUMENTACION_REPRESENTANTE_LEGAL] FOREIGN KEY ([ID_REPRESENTANTE_LEGAL]) REFERENCES [bio].[REPRESENTANTES_LEGALES] ([ID])
);

-- REPRESENTANTES LEGALES
----------------------------------
CREATE TABLE [bio].[REPRESENTANTES_LEGALES] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_PERSONA_MORAL]     INT              NOT NULL
    ,[RFC]                  VARCHAR(13)
    ,[CURP]                 VARCHAR(18)
    ,[TIPO_RELACION]        VARCHAR(100)
    ,[NOMBRE]               VARCHAR(100)
    ,[PATERNO]              VARCHAR(100)
    ,[MATERNO]              VARCHAR(100)
    ,[NUMERO_SERIE_FIEL]    VARCHAR(50)

    ,CONSTRAINT [PK_REPRESENTANTES_LEGALES_ID]         PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_REPRESENTANTES_LEGALES_PERSONA_MORAL] FOREIGN KEY ([ID_PERSONA_MORAL]) REFERENCES [bio].[PERSONAS_MORALES] ([ID])
);

-- BENEFICIARIOS
----------------------------------
CREATE TABLE [bio].[BENEFICIARIOS] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_PERSONA_FISICA]    INT              NOT NULL
    ,[NOMBRE]               VARCHAR(100)
    ,[SEGUNDO]              VARCHAR(100)
    ,[PATERNO]              VARCHAR(100)
    ,[MATERNO]              VARCHAR(100)
    ,[RFC]                  VARCHAR(13)
    ,[FECHA_NACIMIENTO]     DATE
    ,[PORCENTAJE]           DECIMAL(5,2)

    ,CONSTRAINT [PK_BENEFICIARIOS_ID]          PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_BENEFICIARIOS_PERSONA_FISICA] FOREIGN KEY ([ID_PERSONA_FISICA]) REFERENCES [bio].[PERSONAS_FISICAS] ([ID])
);

-- REFERENCIAS BANCARIAS
----------------------------------
CREATE TABLE [bio].[REFERENCIAS_BANCARIAS] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_PERSONA_FISICA]    INT              NOT NULL
    ,[BANCO]                VARCHAR(100)
    ,[CUENTA]               VARCHAR(50)
    ,[CLABE]                VARCHAR(18)

    ,CONSTRAINT [PK_REFERENCIAS_BANCARIAS_ID]          PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_REFERENCIAS_BANCARIAS_PERSONA_FISICA] FOREIGN KEY ([ID_PERSONA_FISICA]) REFERENCES [bio].[PERSONAS_FISICAS] ([ID])
);

-- PERFIL TRANSACCIONAL
----------------------------------
CREATE TABLE [bio].[PERFIL_TRANSACCIONAL] (
     [ID]                                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]                           INT              NOT NULL
    ,[NUMERO_APORTACIONES_MENSUALES]        VARCHAR(50)
    ,[IMPORTE_APORTACION_MENSUAL]           VARCHAR(50)
    ,[NUMERO_RETIROS_MENSUALES]             VARCHAR(50)
    ,[IMPORTE_RETIROS_MENSUALES]            VARCHAR(50)

    ,CONSTRAINT [PK_PERFIL_TRANSACCIONAL_ID]       PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_PERFIL_TRANSACCIONAL_CLIENTE]  FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- ESTATUS REGULATORIO
----------------------------------
CREATE TABLE [bio].[ESTATUS_REGULATORIO] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]           INT              NOT NULL
    ,[FATCA]                BIT
    ,[PEP]                  BIT
    ,[TIPO_RIESGO]          VARCHAR(50)

    ,CONSTRAINT [PK_ESTATUS_REGULATORIO_ID]        PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_ESTATUS_REGULATORIO_CLIENTE]   FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- FATCA
----------------------------------
CREATE TABLE [bio].[FATCA] (
     [ID]                               INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]                       INT              NOT NULL
    ,[PRODUCTO_CONTRATADO]              VARCHAR(200)
    ,[RELACION_ENTIDAD_FINANCIERA]      VARCHAR(200)
    ,[NOMBRE_COMERCIAL]                 VARCHAR(200)
    ,[GRUPO_EMPRESARIAL]                BIT

    ,CONSTRAINT [PK_FATCA_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_FATCA_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- PEP (Personas Políticamente Expuestas)
----------------------------------
CREATE TABLE [bio].[PEP] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_CLIENTE]           INT              NOT NULL
    ,[TIPO_CREDITO]         VARCHAR(200)

    ,CONSTRAINT [PK_PEP_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_PEP_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [bio].[CLIENTES] ([ID])
);

-- RESIDENCIAS FISCALES
----------------------------------
CREATE TABLE [bio].[RESIDENCIAS_FISCALES] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_FATCA]             INT              NOT NULL
    ,[PAIS]                 VARCHAR(100)
    ,[RFC]                  VARCHAR(13)
    ,[TIN]                  VARCHAR(50)

    ,CONSTRAINT [PK_RESIDENCIAS_FISCALES_ID]       PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_RESIDENCIAS_FISCALES_FATCA]    FOREIGN KEY ([ID_FATCA]) REFERENCES [bio].[FATCA] ([ID])
);

-- CONSORCIO ACCIONISTAS
----------------------------------
CREATE TABLE [bio].[CONSORCIO_ACCIONISTAS] (
     [ID]                   INT              IDENTITY(1,1) NOT NULL
    ,[ID_FATCA]             INT              NOT NULL
    ,[NOMBRE]               VARCHAR(100)
    ,[PATERNO]              VARCHAR(100)
    ,[MATERNO]              VARCHAR(100)

    ,CONSTRAINT [PK_CONSORCIO_ACCIONISTAS_ID]      PRIMARY KEY ([ID])
    ,CONSTRAINT [FK_CONSORCIO_ACCIONISTAS_FATCA]   FOREIGN KEY ([ID_FATCA]) REFERENCES [bio].[FATCA] ([ID])
);
GO

-- ÍNDICES RECOMENDADOS PARA MEJORAR PERFORMANCE
----------------------------------

-- Índices para CLIENTES
CREATE INDEX [IX_CLIENTES_TIPO_PERSONA] ON [bio].[CLIENTES]([TIPO_PERSONA]);
CREATE INDEX [IX_CLIENTES_ESTATUS] ON [bio].[CLIENTES]([ESTATUS]);
CREATE INDEX [IX_CLIENTES_INCODE_SESSION] ON [bio].[CLIENTES]([ID_INCODE_SESSION]);

-- Índices para PERSONAS_FISICAS
CREATE INDEX [IX_PERSONAS_FISICAS_CLIENTE] ON [bio].[PERSONAS_FISICAS]([ID_CLIENTE]);
CREATE INDEX [IX_PERSONAS_FISICAS_RFC] ON [bio].[PERSONAS_FISICAS]([PATERNO], [MATERNO], [NOMBRE]);

-- Índices para PERSONAS_MORALES
CREATE INDEX [IX_PERSONAS_MORALES_CLIENTE] ON [bio].[PERSONAS_MORALES]([ID_CLIENTE]);
CREATE INDEX [IX_PERSONAS_MORALES_RFC] ON [bio].[PERSONAS_MORALES]([RFC]);
CREATE INDEX [IX_PERSONAS_MORALES_RAZON_SOCIAL] ON [bio].[PERSONAS_MORALES]([RAZON_SOCIAL]);

-- Índices para DIRECCIONES
CREATE INDEX [IX_DIRECCIONES_CLIENTE] ON [bio].[DIRECCIONES]([ID_CLIENTE]);
CREATE INDEX [IX_DIRECCIONES_REPRESENTANTE] ON [bio].[DIRECCIONES]([ID_REPRESENTANTE_LEGAL]);
CREATE INDEX [IX_DIRECCIONES_TIPO] ON [bio].[DIRECCIONES]([TIPO_DIRECCION]);

-- Índices para CONTACTOS
CREATE INDEX [IX_CONTACTOS_CLIENTE] ON [bio].[CONTACTOS]([ID_CLIENTE]);
CREATE INDEX [IX_CONTACTOS_REPRESENTANTE] ON [bio].[CONTACTOS]([ID_REPRESENTANTE_LEGAL]);
CREATE INDEX [IX_CONTACTOS_EMAIL] ON [bio].[CONTACTOS]([EMAIL]);

-- Índices para DOCUMENTACION
CREATE INDEX [IX_DOCUMENTACION_CLIENTE] ON [bio].[DOCUMENTACION]([ID_CLIENTE]);
CREATE INDEX [IX_DOCUMENTACION_REPRESENTANTE] ON [bio].[DOCUMENTACION]([ID_REPRESENTANTE_LEGAL]);
CREATE INDEX [IX_DOCUMENTACION_RFC] ON [bio].[DOCUMENTACION]([RFC]);
CREATE INDEX [IX_DOCUMENTACION_CURP] ON [bio].[DOCUMENTACION]([CURP]);

-- Índices para REPRESENTANTES_LEGALES
CREATE INDEX [IX_REPRESENTANTES_LEGALES_PERSONA_MORAL] ON [bio].[REPRESENTANTES_LEGALES]([ID_PERSONA_MORAL]);
CREATE INDEX [IX_REPRESENTANTES_LEGALES_RFC] ON [bio].[REPRESENTANTES_LEGALES]([RFC]);

-- Índices para BENEFICIARIOS
CREATE INDEX [IX_BENEFICIARIOS_PERSONA_FISICA] ON [bio].[BENEFICIARIOS]([ID_PERSONA_FISICA]);
CREATE INDEX [IX_BENEFICIARIOS_RFC] ON [bio].[BENEFICIARIOS]([RFC]);

-- Índices para REFERENCIAS_BANCARIAS
CREATE INDEX [IX_REFERENCIAS_BANCARIAS_PERSONA_FISICA] ON [bio].[REFERENCIAS_BANCARIAS]([ID_PERSONA_FISICA]);

-- Índices para PERFIL_TRANSACCIONAL
CREATE INDEX [IX_PERFIL_TRANSACCIONAL_CLIENTE] ON [bio].[PERFIL_TRANSACCIONAL]([ID_CLIENTE]);

-- Índices para ESTATUS_REGULATORIO
CREATE INDEX [IX_ESTATUS_REGULATORIO_CLIENTE] ON [bio].[ESTATUS_REGULATORIO]([ID_CLIENTE]);
CREATE INDEX [IX_ESTATUS_REGULATORIO_FATCA] ON [bio].[ESTATUS_REGULATORIO]([FATCA]);
CREATE INDEX [IX_ESTATUS_REGULATORIO_PEP] ON [bio].[ESTATUS_REGULATORIO]([PEP]);

-- Índices para FATCA
CREATE INDEX [IX_FATCA_CLIENTE] ON [bio].[FATCA]([ID_CLIENTE]);

-- Índices para PEP
CREATE INDEX [IX_PEP_CLIENTE] ON [bio].[PEP]([ID_CLIENTE]);

-- Índices para RESIDENCIAS_FISCALES
CREATE INDEX [IX_RESIDENCIAS_FISCALES_FATCA] ON [bio].[RESIDENCIAS_FISCALES]([ID_FATCA]);
CREATE INDEX [IX_RESIDENCIAS_FISCALES_PAIS] ON [bio].[RESIDENCIAS_FISCALES]([PAIS]);

-- Índices para CONSORCIO_ACCIONISTAS
CREATE INDEX [IX_CONSORCIO_ACCIONISTAS_FATCA] ON [bio].[CONSORCIO_ACCIONISTAS]([ID_FATCA]);

-- Índices para INCODE
CREATE INDEX [IX_INCODE_FLOW_PERSON_TYPE] ON [bio].[INCODE_FLOW]([PERSON_TYPE]);
CREATE INDEX [IX_INCODE_FLOW_ACTIVE] ON [bio].[INCODE_FLOW]([ACTIVE]);
CREATE INDEX [IX_INCODE_SESSION_FLOW] ON [bio].[INCODE_SESSION]([FLOW]);
CREATE INDEX [IX_INCODE_SESSION_CLIENT] ON [bio].[INCODE_SESSION]([CLIENT]);
CREATE INDEX [IX_INCODE_SESSION_ACTIVE] ON [bio].[INCODE_SESSION]([ACTIVE]);